abdominal_pain(alcoholic_hepatitis).
abdominal_pain(chronic_cholestasis).
abdominal_pain(hepatitis_a).
abdominal_pain(hepatitis_b).
abdominal_pain(hepatitis_d).
abdominal_pain(hepatitis_e).
abdominal_pain(jaundice).
abdominal_pain(peptic_ulcer_diseae).
abdominal_pain(typhoid).
abnormal_menstruation(hyperthyroidism).
abnormal_menstruation(hypothyroidism).
acidity(gerd).
acidity(migraine).
acute_liver_failure(hepatitis_e).
altered_sensorium(paralysis_brain_hemorrhage).
anxiety(hypoglycemia).
back_pain(cervical_spondylosis).
back_pain(dengue).
belly_pain(typhoid).
blackheads(acne).
bladder_discomfort(urinary_tract_infection).
blister(impetigo).
blood_in_sputum(tuberculosis).
bloody_stool(dimorphic_hemmorhoids_piles).
blurred_and_distorted_vision(diabetes).
blurred_and_distorted_vision(hypoglycemia).
blurred_and_distorted_vision(migraine).
breathlessness(bronchial_asthma).
breathlessness(heart_attack).
breathlessness(pneumonia).
breathlessness(tuberculosis).
brittle_nails(hypothyroidism).
bruising(varicose_veins).
burning_micturition(drug_reaction).
burning_micturition(urinary_tract_infection).
chest_pain(common_cold).
chest_pain(gerd).
chest_pain(heart_attack).
chest_pain(hypertension).
chest_pain(pneumonia).
chest_pain(tuberculosis).
chills(allergy).
chills(common_cold).
chills(dengue).
chills(malaria).
chills(pneumonia).
chills(tuberculosis).
chills(typhoid).
cold_hands_and_feets(hypothyroidism).
coma(hepatitis_e).
congestion(common_cold).
constipation(dimorphic_hemmorhoids_piles).
constipation(typhoid).
continuous_feel_of_urine(urinary_tract_infection).
continuous_sneezing(allergy).
continuous_sneezing(common_cold).
cough(bronchial_asthma).
cough(common_cold).
cough(gerd).
cough(pneumonia).
cough(tuberculosis).
cramps(varicose_veins).
dark_urine(hepatitis_a).
dark_urine(hepatitis_b).
dark_urine(hepatitis_d).
dark_urine(hepatitis_e).
dark_urine(jaundice).
dehydration(gastroenteritis).
depression(hypothyroidism).
depression(migraine).
diarrhoea(gastroenteritis).
diarrhoea(hepatitis_a).
diarrhoea(hyperthyroidism).
diarrhoea(malaria).
diarrhoea(typhoid).
dischromic_patches(fungal_infection).
distention_of_abdomen(alcoholic_hepatitis).
dizziness(cervical_spondylosis).
dizziness(hypertension).
dizziness(hypothyroidism).
drying_and_tingling_lips(hypoglycemia).
enlarged_thyroid(hypothyroidism).
excessive_hunger(diabetes).
excessive_hunger(hyperthyroidism).
excessive_hunger(hypoglycemia).
excessive_hunger(migraine).
extra_marital_contacts(aids).
family_history(bronchial_asthma).
family_history(hepatitis_c).
fast_heart_rate(hyperthyroidism).
fast_heart_rate(pneumonia).
fatigue(bronchial_asthma).
fatigue(chicken_pox).
fatigue(common_cold).
fatigue(dengue).
fatigue(diabetes).
fatigue(hepatitis_b).
fatigue(hepatitis_c).
fatigue(hepatitis_d).
fatigue(hepatitis_e).
fatigue(hyperthyroidism).
fatigue(hypoglycemia).
fatigue(hypothyroidism).
fatigue(jaundice).
fatigue(pneumonia).
fatigue(tuberculosis).
fatigue(typhoid).
fatigue(varicose_veins).
fluid_overload(alcoholic_hepatitis).
foul_smell_of_urine(urinary_tract_infection).
headache(chicken_pox).
headache(common_cold).
headache(dengue).
headache(hypertension).
headache(hypoglycemia).
headache(malaria).
headache(migraine).
headache(paralysis_brain_hemorrhage).
headache(typhoid).
headache(vertigo_paroymsal_positional_vertigo).
high_fever(aids).
high_fever(bronchial_asthma).
high_fever(chicken_pox).
high_fever(common_cold).
high_fever(dengue).
high_fever(hepatitis_e).
high_fever(impetigo).
high_fever(jaundice).
high_fever(malaria).
high_fever(pneumonia).
high_fever(tuberculosis).
high_fever(typhoid).
hip_joint_pain(osteoarthristis).
history_of_alcohol_consumption(alcoholic_hepatitis).
increased_appetite(diabetes).
indigestion(migraine).
indigestion(peptic_ulcer_diseae).
inflammatory_nails(psoriasis).
internal_itching(peptic_ulcer_diseae).
irregular_sugar_level(diabetes).
irritability(hyperthyroidism).
irritability(hypoglycemia).
irritability(hypothyroidism).
irritability(migraine).
irritation_in_anus(dimorphic_hemmorhoids_piles).
itching(chicken_pox).
itching(chronic_cholestasis).
itching(drug_reaction).
itching(fungal_infection).
itching(hepatitis_b).
itching(jaundice).
joint_pain(dengue).
joint_pain(hepatitis_a).
joint_pain(hepatitis_d).
joint_pain(hepatitis_e).
joint_pain(osteoarthristis).
joint_pain(psoriasis).
knee_pain(osteoarthristis).
lack_of_concentration(hypertension).
lethargy(chicken_pox).
lethargy(diabetes).
lethargy(hepatitis_b).
lethargy(hypothyroidism).
loss_of_appetite(chicken_pox).
loss_of_appetite(chronic_cholestasis).
loss_of_appetite(dengue).
loss_of_appetite(hepatitis_a).
loss_of_appetite(hepatitis_b).
loss_of_appetite(hepatitis_c).
loss_of_appetite(hepatitis_d).
loss_of_appetite(hepatitis_e).
loss_of_appetite(peptic_ulcer_diseae).
loss_of_appetite(tuberculosis).
loss_of_balance(cervical_spondylosis).
loss_of_balance(hypertension).
loss_of_balance(vertigo_paroymsal_positional_vertigo).
loss_of_smell(common_cold).
malaise(chicken_pox).
malaise(common_cold).
malaise(dengue).
malaise(hepatitis_b).
malaise(pneumonia).
malaise(tuberculosis).
mild_fever(chicken_pox).
mild_fever(hepatitis_a).
mild_fever(tuberculosis).
mood_swings(hyperthyroidism).
mood_swings(hypothyroidism).
movement_stiffness(arthritis).
mucoid_sputum(bronchial_asthma).
muscle_pain(common_cold).
muscle_pain(dengue).
muscle_pain(hepatitis_a).
muscle_pain(malaria).
muscle_wasting(aids).
muscle_weakness(arthritis).
muscle_weakness(hyperthyroidism).
nausea(chronic_cholestasis).
nausea(dengue).
nausea(hepatitis_a).
nausea(hepatitis_c).
nausea(hepatitis_d).
nausea(hepatitis_e).
nausea(hypoglycemia).
nausea(malaria).
nausea(typhoid).
nausea(vertigo_paroymsal_positional_vertigo).
neck_pain(cervical_spondylosis).
neck_pain(osteoarthristis).
nodal_skin_eruptions(fungal_infection).
obesity(diabetes).
obesity(varicose_veins).
pain_behind_the_eyes(dengue).
pain_during_bowel_movements(dimorphic_hemmorhoids_piles).
pain_in_anal_region(dimorphic_hemmorhoids_piles).
painful_walking(arthritis).
painful_walking(osteoarthristis).
palpitations(hypoglycemia).
passage_of_gases(peptic_ulcer_diseae).
patches_in_throat(aids).
phlegm(common_cold).
phlegm(pneumonia).
phlegm(tuberculosis).
polyuria(diabetes).
prominent_veins_on_calf(varicose_veins).
puffy_face_and_eyes(hypothyroidism).
pus_filled_pimples(acne).
receiving_blood_transfusion(hepatitis_b).
receiving_unsterile_injections(hepatitis_b).
red_sore_around_nose(impetigo).
red_spots_over_body(chicken_pox).
red_spots_over_body(dengue).
redness_of_eyes(common_cold).
restlessness(diabetes).
restlessness(hyperthyroidism).
runny_nose(common_cold).
rusty_sputum(pneumonia).
scurring(acne).
shivering(allergy).
silver_like_dusting(psoriasis).
sinus_pressure(common_cold).
skin_peeling(psoriasis).
skin_rash(acne).
skin_rash(chicken_pox).
skin_rash(dengue).
skin_rash(drug_reaction).
skin_rash(fungal_infection).
skin_rash(impetigo).
skin_rash(psoriasis).
slurred_speech(hypoglycemia).
small_dents_in_nails(psoriasis).
spinning_movements(vertigo_paroymsal_positional_vertigo).
spotting_urination(drug_reaction).
stiff_neck(arthritis).
stiff_neck(migraine).
stomach_bleeding(hepatitis_e).
stomach_pain(drug_reaction).
stomach_pain(gerd).
sunken_eyes(gastroenteritis).
sweating(heart_attack).
sweating(hyperthyroidism).
sweating(hypoglycemia).
sweating(malaria).
sweating(pneumonia).
sweating(tuberculosis).
swelled_lymph_nodes(chicken_pox).
swelled_lymph_nodes(common_cold).
swelled_lymph_nodes(tuberculosis).
swelling_joints(arthritis).
swelling_joints(osteoarthristis).
swelling_of_stomach(alcoholic_hepatitis).
swollen_blood_vessels(varicose_veins).
swollen_extremeties(hypothyroidism).
swollen_legs(varicose_veins).
throat_irritation(common_cold).
toxic_look_typhos(typhoid).
ulcers_on_tongue(gerd).
unsteadiness(vertigo_paroymsal_positional_vertigo).
visual_disturbances(migraine).
vomiting(alcoholic_hepatitis).
vomiting(chronic_cholestasis).
vomiting(dengue).
vomiting(gastroenteritis).
vomiting(gerd).
vomiting(heart_attack).
vomiting(hepatitis_a).
vomiting(hepatitis_d).
vomiting(hepatitis_e).
vomiting(hypoglycemia).
vomiting(jaundice).
vomiting(malaria).
vomiting(paralysis_brain_hemorrhage).
vomiting(peptic_ulcer_diseae).
vomiting(tuberculosis).
vomiting(typhoid).
vomiting(vertigo_paroymsal_positional_vertigo).
watering_from_eyes(allergy).
weakness_in_limbs(cervical_spondylosis).
weakness_of_one_body_side(paralysis_brain_hemorrhage).
weight_gain(hypothyroidism).
weight_loss(diabetes).
weight_loss(hyperthyroidism).
weight_loss(jaundice).
weight_loss(tuberculosis).
yellow_crust_ooze(impetigo).
yellow_urine(hepatitis_b).
yellowing_of_eyes(chronic_cholestasis).
yellowing_of_eyes(hepatitis_a).
yellowing_of_eyes(hepatitis_b).
yellowing_of_eyes(hepatitis_c).
yellowing_of_eyes(hepatitis_d).
yellowing_of_eyes(hepatitis_e).
yellowing_of_eyes(tuberculosis).
yellowish_skin(alcoholic_hepatitis).
yellowish_skin(chronic_cholestasis).
yellowish_skin(hepatitis_a).
yellowish_skin(hepatitis_b).
yellowish_skin(hepatitis_c).
yellowish_skin(hepatitis_d).
yellowish_skin(hepatitis_e).
yellowish_skin(jaundice).